org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dcom.android.ddmlib.timeout=600000 -Dcom.android.ddmlib.pendingReqTimeout=600000
org.gradle.configuration-cache=true
kotlin.code.style=official
android.disallowKotlinSourceSets=false
android.useAndroidX=true
android.adbOptions.timeOutInMs=600000
systemProp.com.android.ddmlib.timeout=600000
systemProp.ADB_INSTALL_TIMEOUT=10


